/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as CreateOfferRouteImport } from './routes/createOffer'
import { Route as IndexRouteImport } from './routes/index'

const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOfferRoute = CreateOfferRouteImport.update({
  id: '/createOffer',
  path: '/createOffer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createOffer': typeof CreateOfferRoute
  '/listings': typeof ListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createOffer': typeof CreateOfferRoute
  '/listings': typeof ListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/createOffer': typeof CreateOfferRoute
  '/listings': typeof ListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createOffer' | '/listings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createOffer' | '/listings'
  id: '__root__' | '/' | '/createOffer' | '/listings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateOfferRoute: typeof CreateOfferRoute
  ListingsRoute: typeof ListingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createOffer': {
      id: '/createOffer'
      path: '/createOffer'
      fullPath: '/createOffer'
      preLoaderRoute: typeof CreateOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateOfferRoute: CreateOfferRoute,
  ListingsRoute: ListingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
